### ISSUE TITLE
modal in hidden tab shown when going landscape

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation-tabs#78] opened 2018-12-14 13:20 UTC
### Current behaviour

ONLY ON ANDROID:
When in a tab and going landscape, opening a Modal, that Modal get's rendered. But when I then go back to portrait, visit another tab, and then again go to landscape, the supposedly hidden Modal get's rendered again.

### Expected behaviour

No hidden modal to be rendered.

### Code sample

https://snack.expo.io/@morriz/tab-issues:-hidden-modal-shown-on-android-only

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 9 (qemu emulator)
| react-native          | expo 31
| react-navigation-tabs | 1.0.1
| node                  | 11.2
| npm or yarn           | npm 6.4.1

**Comment by Morriz** [comment] 2018-12-14 13:55
I understand that the example code I produced creates a tight coupling in the component itself, that outside code can not interfere with. But I strongly suggest that react-navigation provides a wrapped Component that checks for conditions before it renders. That allows us to extend from, lets say `RNTComponent` so we know the view follows the tab configuration settings.

**Comment by brentvatne** [comment] 2018-12-14 19:16
> on that note: why does the tab container get rendered when it's hidden in the first place? Especially when it has lazy true??

put an alert inside the render function for ModalScreen and you will see it is lazily rendered (not rendered until the first time that you switch to it)

> But I strongly suggest that react-navigation provides a wrapped Component that checks for conditions before it renders.

not sure I follow, but you can create a rfc that describes this and i'd be happy to read it over!

<hr />

i don't recommend using the Modal component from react-native, it'd be better to use something that is just implemented in js. what you've encountered here is just a bug in react-native Modal on android :O

**Comment by fbartho** [comment] 2018-12-14 21:52
I'm exhibiting a similar issue -- we tried to upgrade to react-navigation 3.0 a couple weeks ago and it worked for everything except it started causing crashes.

What we discovered: when popping from a deep modal + stack navigator combo, back to a new tab in a tab navigator as the first screen in a different stack navigator, we were seeing all the intermediate screens (that were being popped away) receive a re-render, except that navigation params were missing. These screens required their navigation params, therefore they crashed.

I hadn't reported this issue yet because I haven't had time to make a minimal repro, but I'm looking to do that next week.  -- maybe this information is useful as is, though? /cc @brentvatne

**Comment by Morriz** [comment] 2018-12-15 10:50
> > on that note: why does the tab container get rendered when it's hidden in the first place? Especially when it has lazy true??
> 
> put an alert inside the render function for ModalScreen and you will see it is lazily rendered (not rendered until the first time that you switch to it)

I have updated my other snack like that to show exactly what I mean: the second time it gets rendered while hidden. But why does it get rendered again when it's hidden (when lazy)?

See that snack here: https://snack.expo.io/@morriz/tab-issues:-hidden-tab-container-gets-re-rendered-when-lazy=true

> i don't recommend using the Modal component from react-native, it'd be better to use something that is just implemented in js. what you've encountered here is just a bug in react-native Modal on android :O

I indeed do think the case I described here is about an android modal bug, but like I said there's probably also a 'lazy' bug (as reported here: https://github.com/react-navigation/react-navigation-tabs/issues/79

Thanks for the suggestion, I will look into it. Any idea how to show a full screen view without it?

**Comment by Morriz** [comment] 2018-12-15 10:56
@fbartho for what it's worth, I am now detecting `willFocus` and `willBlur` to set a `isVisible` flag that gets checked in `render`. I just return an empty view upon `!isVisible` instead of the Modal.

**Comment by brentvatne** [comment] 2018-12-15 19:07
it isn't a lazy bug, i tested it and also explained to you that you can just add an alert to render to prove to yourself that lazy works as expected. closing this but if someone can make an issue that demonstrates a bug that isn't just caused by react-native's modal component then i can look into it

**Closed by brentvatne** 2018-12-15 19:07 UTC
