### ISSUE TITLE
I want to hide bottom tab bar when keyboard appear

### ISSUE THREAD

**Issue by tndyd5390** [react-navigation/react-navigation-tabs#64] opened 2018-11-05 02:21 UTC
i have some problem with bottomtabnavigator,
bottomtab dosen't disappear when keyboard is activated
how can i hide my bottom tab bar when keyboard is activated???

and this is my code
`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image} from 'react-native';
import {createBottomTabNavigator, withNavigation} from 'react-navigation';
import Icon from 'react-native-vector-icons/Ionicons';
import IconFontAwesome from 'react-native-vector-icons/FontAwesome';
import Explore from './screens/Explore';
import Reservation from './screens/Reservation';
import Saved from './screens/Saved';
import Chat from './screens/Chat';
import Profile from './screens/Profile';
import Colors from './utils/Colors';

export default createBottomTabNavigator({
  Explore : {
    screen : Explore,
    navigationOptions : {
      tabBarLabel : '검색하기',
      tabBarIcon : ({tintColor}) => (
        //<Image source={require('./img/img.png')} style={{height : 24, width : 24, tintColor : tintColor}}/>
        <Icon name='ios-search' color={tintColor} size={24}/>
      )
    }
  },
  Saved : {
    screen : Reservation,
    navigationOptions : {
      tabBarLabel : '예약보기',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='calendar' color={tintColor} size={24}/>
      )
    }
  },
  Trips : {
    screen : Chat,
    navigationOptions : {
      tabBarLabel : '대화하기',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='comments' color={tintColor} size={24}/>
      )
    }
  },
  Profile : {
    screen : withNavigation(Profile),
    navigationOptions : {
      tabBarLabel : '프로필',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='user' color={tintColor} size={24}/>
      )
    }
  },
},
{
  tabBarPosition : 'bottom',
  swipeEnabled : false,
  tabBarOptions : {
    activeTintColor : 'red',
    inactiveTintColor : 'grey',
    style : {
      //backgroundColor : 'white',
      backgroundColor : Colors.bottomNavigatorGrey,
      borderTopWidth : 0,
      shadowOffset : {width : 5, height : 3},
      shadowColor : 'black',
      shadowOpacity : 0.5,
      elevation : 5
    }
  }
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  }
});
`

`import React, {Component} from 'react';
import {
  Platform, 
  StyleSheet, 
  Text, 
  View,
  Dimensions,
  Image,
  TextInput,
  Keyboard,
  TouchableOpacity
} from 'react-native';
import Colors from '../utils/Colors';
import Icon from 'react-native-vector-icons/FontAwesome';
import PropTypes from 'prop-types';
const{height, width} = Dimensions.get('window');

class Profile extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View>
          <Image source={require('../../img/user.png')} style={{width : 200, height : 200, marginTop : 30}}/>
        </View>
        <View style={{width : width-60}}>
          <Text style={styles.idText}>아이디</Text>
          <TextInput style={{borderBottomWidth : 1, paddingTop : 5, paddingBottom : 5}}/>
        </View>
      </View>
    );
  }
}

export default Profile;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
  }, 
  idText : {
    fontSize : 20,
    marginTop : 10
  }
});`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | react-native-cli 2.0.1
| react-navigation-tabs | 2.0.4
| node                  | 10.6.0
| npm or yarn           | npm 6.1.0

**Comment by vkcyan** [comment] 2018-12-13 01:02
Hello, if you don't want the input box to start the bottom navigation bar, please do this.
Replace one line of code in `android\app\src\main\AndroidManifest.xml` inside the project
I did this, I don't know if it is feasible for you.
```xml
<application
      <!--//......-->
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
         <!-- android:windowSoftInputMode="adjustResize" Change to the following -->       
        android:windowSoftInputMode="stateAlwaysHidden|adjustPan">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
```

**Comment by smitthakkar1** [comment] 2019-02-10 23:06
This doesn't work for me

**Comment by satya164** [comment] 2019-03-12 22:33
Duplicate of #16

**Closed by satya164** 2019-03-12 22:33 UTC
