### ISSUE TITLE
TabBarIcon: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by hammadxoho** [react-navigation/react-navigation-tabs#86] opened 2019-01-10 17:21 UTC
Getting this error 
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of "TabBarIcon".

Following is the code i have:- issue in the build for ios 

import React from 'react';
import {createStackNavigator, createBottomTabNavigator, createSwitchNavigator} from 'react-navigation';
import {Alert} from 'react-native';
import { FontAwesome } from "react-native-vector-icons";

I was using Expo.io before and it worked all fine, but after ejecting and removing expo completely (not using expokit), i am starting to get these issues

**Comment by satya164** [comment] 2019-03-12 22:38
Make sure you're passing a valid react component. Closing this since it's most likely an issue with your code. If you believe it's an issue in the library, please create a new issue with a reproducible example.

**Closed by satya164** 2019-03-12 22:38 UTC
